# Interaction/discourse Centered

## Evolutionary Theories

theoretical framework to study biology and interpersonal communication (i.e., biosocial approach)

Some traits remain relatively stable in species.

Five principles:

1.  Basic Theory of evolution: "perpetual change in the living world where nothing is constant or repeated exactly"

2.  Common decent

3.  Multiplication of species

4.  gradualism

5.  natural selection

    1.  Individuals are variable. (i.e., variation among organism in the same familial lineage)

    2.  Advantageous traits are passed on to off-spring.

    3.  Individuals produce more offspring than the environment can support. Then, scarcity of resources kick in to
        favor individuals that have traits more advantages in acquiring resources (i.e., Adaptation), which operates at
        the genetic level (not individual).

    4.  traits are passed on gradually which lead to new species in the population

[@Tooby_2015] evolutionary psychology study the functions of brain, which is known as psychological adaptation that
evolve to solve problems in its environment.

Limitation:

-   Controversial regarding sex (i.e., biological make-up of men and women are different). Biological determinism is in
    contrast to "bi-directional nature of hormonal responses and the fact that individuals' communication can influence
    their physiological responses and vice versa."
-   Controversial over culture and individual differences:

Application:

-   [@Denes_2016] "high testosterone/no orgasm individuals may be the least likely to experience the beneficial effects
    of post sex communication."
-   [@Aloia_2014] "positive association between conflict intensity and cortisol reactivity, and this association was
    attenuated for individuals who reported higher, rather than lower, levels of childhood exposure to familial verbal
    aggression."

### Affection Exchange Theory

(AET) [@Floyd_2001] contemplates that "people give and receive affection in ways that are adaptive or evolutionarily
advantageous for their relationship." There is evidence that affection reduces stress.

Assumptions of AET:

-   procreation and survival are superodinate human goals
-   Communication helps achieve these goals (consciously or unconsciously)
-   traits that are desirable (i.e., advantageous) for superordinate goals will be passed on
-   human communicative behaviors are only partially controlled by humans.

AET's propositions:

-   "the need and capacity for affection are inborn"

    -   we don't need to learn to feel affection(i.e., innate)

    -   the need for affection is fundamental

-   "affectionate feelings and affectionate expression are distinct experiences that often, but need not, covary"

-   "affectionate communication is adaptive with respect to human viability and fertility"

-   "humans vary in their optimal tolerances for affection and affectionate behavior"

-   "affectionate behaviors that violate the range of optimal tolerance are physiologically aversive"

[@Floyd_1998] propose 3 forms of affection display:

-   Verbal communication (e.g., spoken or written)
-   Direct nonverbal (e.g., nonlinguistic or paralinguistic behaviors)
-   Indirect Nonverbal (e.g., behaviors that convey affection via social or material support)

Types of affectionate communication research:

-   Relationships: certain relationships are more affectionate than others because it relates to the relatedness of
    genes' survivability

    -   fathers gives more attention to children with higher probability to reproduce.

    -   "humans engage in affectionate behaviors, both genuinely and deceptively, within selective romantic
        relationships in order to increase relational trust, closeness, and satisfaction.", which in turn, increase
        survival and procreation.

-   Health

    -   One can have health benefits by offering affection.

    -   "highly affectionate people report higher self-esteem, general mental health, social engagement, and life
        satisfaction,a s well as lower susceptibility to depression and stress, than less-affectionate
        people"[@Floyd_2002]

Application:

[@Floyd_2009]

-   kissing improves perceived stress, relationship satisfaction, and total serum cholesterol

<br>

[@Horan_2013]

-   motivation for deceptive affection:

    -   face-saving

    -   conflict management/ avoidance

    -   emotion management

-   feelings of affection is different from communicating affection

    -   feeling affection: the feeling of warmth and fondness toward an individual

    -   communicating affection: feelings of fondness, support, and love

<br>

[@Davis_2019]

-   Controlling images (.e.g, angry black woman or mammy). Black women are thought to be self-sufficient, perseverant,
    authentic.

-   Strong Black woman collective theory: "Black women enact communication behaviors that affirm strength in each other
    ... to delineate a safe space to concurrently promote solidarity within the collective and confront oppressive
    force."

    -   Black women use "distinct communication practices (i.e., code-switching, assertive and verbal messages, and
        culturally-nuanced speech codes)"

    -   the assemblage of Black women

    -   members reinforce each others virtues of strength

    -   enable members to confront oppressive structure, but also impede vulnerability and emotionality within

-   Strength regulation like emotion regulation

-   "strength regulation contributed to more derogative comments about aggressors during supportive discussions, and
    support seekers were less satisfied in their relationships with white women after the derogative conversations"

<br>

[@Gilchrist_Petty_2019]

-   engaged-to-be-married has the highest negative attitudes regarding cross-sex best friendships.
-   attitudes toward cross-sex best friendships mediate the relationship between (how jealousy experienced and
    expressed) and (reactive jealousy experience and destructive jealousy expression)

<br>

### Tend and Befriend theory

Under the fight or flight framework, people tend to affiliate with others under stress [@Taylor_2012]. Women have
different level of fight or flight tendencies, which is due to hormones and evolutionary tendencies.

### Attachment theory

[@Bowlby_1982] As child, we form attachments to our parents, which affect how we perceive and approach relationship in
the future. Oxytocin is a hormone that facilitates social bonds [@Campbell_2010]

## Intergroup Theorizing

### Communication Accommodation Theory

Varying communicative styles are reflections of personalities, roles, temperaments, and social identities.

Communication Accommodation theory (CAT) explains why we communicate differently with different people (i.e., our
communication choices change based on the relational, identity we engage in).

Accommodation is "a process concerned with how we can reduce (and, in some cases, even magnify) communicative
differences between people in interaction" [@Baxter_2008, pp. 237]. It "enhances interpersonal similarities, and reduces
uncertainties about the other" [@Baxter_2008, pp. 237]. Speakers will be seen as more competent and credible
[@Aune_1993]. Accommodation manifests via convergence in language (i.e., dialect), nonverbal cues (e.g., speech rate,
posture) [@Li_2001]. Those with more social power are often accommodated. *(however, I think less social power should be
accommodated, for example, patients and doctors, benefactors and beneficiaries)*

Nonaccommodacaiton can signal lack of respect or liking to the other person (could be intentional or unintentional), or
authenticity. Divergence signal membership in groups, culture, and communities (their social identity).

Symmetricality and accommodation lead to strengthened interpersonal relations, and vice versa.

Principles of accommodation:

1.  Speakers will, up to an optimal level, increasingly accommodate the communicative patterns believed characteristic
    of their interactants the more they wish to

    1.  Signal positive face and empathy

    2.  Elicit the other's approval, respect, understanding, trust, compliance, and cooperation

    3.  Develop a closer relationship

    4.  Defuse a potentially volatile situation

    5.  Signal common social identities

2.  When attributed (typically) with positive intent, patterns of perceived accommodation increasingly and cumulatively
    enhance recipients'

    1.  Self-esteem;

    2.  Task, interactional, and job satisfaction;

    3.  Favorable images of the speaker's group, fostering the potential for partnerships to achieve common goals;

    4.  Mutual understanding, felt supportiveness, and life satisfaction;

    5.  Attributions of speaker politeness, empathy, competence, benevolence, and trust.

3.  Speakers will (other interactional motives notwithstanding) increasingly nonaccommodate (e.g., diverge from) the
    communicative patterns believed characteristic of their interactants, the more they wish to signal (or promote)

    1.  Relational dissatisfaction or disaffection with and disrespect for the others' traits, demeanor, actions, or
        social identities.

4.  When attributed with (usually) harmful intent, patterns of perceived nonaccommodation (e.g., divergence) will be

    1.  Evaluated unfavorably as unfriendly, impolite, or communicatively incompetent;

    2.  Reacted to negatively by recipients (e.g., recipients will perceive speaker to be lacking in empathy and trust)

CAT absorbs both interpersonal and intergroup process, even though they are considered orthogonal.

Application:

[@Chen_2016]

-   The characteristics of their communication partner (mediated by specific communication behaviors imagined by the
    participant for two of the three trait dimensions such as overaccommodation for perceptions of competence, humorous
    communication for perceptions of sociability) influences participants' stereotypes of older adult

    -   overaccommendation can be seemed patronizing, which reinforces stereotypes

-   Imagined interaction involves individuals' spontaneous thoughts regarding interpersonal communication with a real
    person, which typically occurs before an actual interaction with the person [@Honeycutt_2014].

-   based on stereotype content model (SCM), groups are stereotyped based on two dimensions: warmth and competence
    [@Fiske_2007]. Later warmth was further segmented into sociability and morality (i.e., trustworthiness)

### Communication Theory of Identity

Stem from psychology and sociology in the 50s and 60s. "Similar to the psychological tradition, the self was still most
often discussed in unitary terms with social roles reserved for the various different manifestations" [@Baxter_2008, pp.
254].

There isn't one core genuine self, but multiple selves (i.e., multiple identities). Self emerges out of one's social
interactions and the perceptions of others [@stryker1979].

Identity/Communication (identity is not separable from communication) leads to communication satisfaction.

CTI conceptualizes layers of identity as both changing and stable, and both subjective and ascribed. 4 layers are
interdependent:

-   Personal: individual, sense of self-being
-   relational: identity defined in relationship, and ascribed
-   Enacted: performance of identity, through verbal and nonverbal messages
-   Communal: how society defines identity and identities (i.e., group membership)

The gap between personal and enacted identities is called identity gaps [@Jung_2004], leads to negative psychological
outcomes (e.g., depression). But it could also help individual try to close the gap (cognitive dissonant).

We want others to value the same attributes that we ourselves value [@Baxter_2008, pp. 261]

<br>

#### Application

[@WILLER_2010]

-   Socially aggressive face threats (SAFTs) are "messages that threaten one's identity or positive face"

-   social aggression can damage self-esteem, social standing.

-   Face is the self or image that people present and expect others to main or support during interaction
    [@Cupach_1994], which includes two desires:

    -   positive face needs: desire for approval, appreciation, and liking

    -   negative face needs: desires for freedom from action ad imposition

-   and two threats

    -   positive face threats: similar to socially aggressive messages. Hence, the authors use the terms SAFTs.

-   Negative affect negatively associated feelings of forgiveness (measured by feelings of revenge and avoidance,
    avoidance)

<br>

[@Nuru_2014]

-   transgender is when "self-identify with a gender that ''contradicts'' socially acceptable gender roles and
    expectations as dictated by external genitalia and assigned birth sex."

    -   "any divergence from conventional social norms that tie gender identity to role expectancy and biological sex"
        [@Bornstein_2013]

-   Gender identity may overlap sexuality, they are two distinct processes of negotiation.

-   Genital sex can differ from social and psychological gender.

-   Gaps between personal, enacted, and relational layers are prevalent.

-   Strategies to mitigate tension:

    -   Closeted enactment

    -   disengagement

    -   passing: intentional disguise to preserve relationship

    -   label changing

<br>

[@Harris_2018]

-   In the context of bullying, studies have traditionally been White-oriented. Hence, there is a need for diverse
    sampling.

-   Due to political climate in 2016, students are reported to be more anxious and new wave of political bullying was on
    the rise.

-   race is a social construct that relates to power, privilege, and systemic oppression. racist draw societal power
    from being members of the majority group. Racism is different from racial prejudice and racial discrimination (i.e.,
    everybody can be racially prejudice, but only macro culture members can be racists).

-   Bullying can happen between group (macro vs. micro cultures), and within group (in-group bullying, i.e., Mexican
    American and Mexican immigrants).

-   Marginalized status triggers victim status

    -   family socioeconomic status (SES) and test scores are correlated

-   Intersectioanality and Race in Bullying

<br>

## Critical Approaches to IPC Research

List of interpersonal communication theories under critical approaches:

-   Relational dialectics Theory
-   Narrative performance Theory
-   Family of Feminist theories

Difference between postmodern critical approach and modern tradition is how power is conceptualized, but both agree that
power has impact on communicative life with the goals of emancipation and empowerment.\
Critical modern hope to free people from socially oppressed system, but postmodern critical scholars view the world as
constant struggle for dominant discourses.

Power definition:

-   Post-positivistic tradition: "as an individual level variable based on the various kinds of resources the individual
    posses" (Berger, 1994).
-   modern critical: "as a systemic construct that exists external to the individuals who operate within those systems."
    [@Baxter_2008, pp. 273]

Critical Modern Tradition:

-   False consciousness: lack of awareness of constraints imposed by system (Pine, 1993).

-   goal: dismantle false consciousness to free people

-   Communication is a reflection of systematic constraint

-   Application:

    -   Gender as a social system, gender is a range of ideals (masculine and feminism).

    -   Relational Labor as a social system

Postmodern Tradition

-   Resist thinking of power as top-down, and advocate for power is bottom-up-and-out dynamics and power is constantly
    met with resistant, which means it is unstable and fluid.

-   Comminciaiton is the social world (not a reflection of it).

-   Application:

    -   Uncertainty as positive precondition for change

    -   Self-making instead of Self-disclosure: individuals are not intact.

To evaluate critical approaches to interpersonal communication, we need to consider:

-   ethics: (1) how your position impacts what is identifiable, and that which is beneficial
-   change: can your change emancipate the marginalized and oppressed?

## Critical Feminist Theories

-   Feminist Theories

    -   "Feminism" is "defined as the belief that men and women are equal and should have equal rights and
        opportunities in all spheres of life---personal, social, work, and public". [@Baxter_2008, pp. 290]

        -   Gender (different from sex): social meaning attached to biological distinct, which is embedded in
            communication

        -   Patriarchy: " a system that reflects primarily the interests, values, perspectives, and experiences of men,
            as a group." [@Baxter_2008, pp. 290]

-   Critical Theories:

    -   "identify prevailing structures and practices that create or uphold disadvantage, inequity, or oppression, and
        to point the way toward alternatives that remote more egalitarian relationships, groups, and societies.
        [@Baxter_2008, pp. 292]

-   The production of the two theories:

    -   The recursive relationship between how cultural structures and practices differently and inequitably shape
        women's and men's lives and communication practice and vice versa.

-   Assumptions:

    -   "members of groups defined by sex, race, and other factors occupy distinct positions in a society - those are
        their social location."

-   Methodological Implication: examination of power that is both formal and informative ones.

-   Power:

    -   in relation to unequal status, privilege.

-   Communication: with less communication on a subject, we'd have less knowledge of it, or even notice it.

    -   Hence, we should name and increase social awareness of women's experiences.

-   Examples

    -   Sexual harassment

    -   Date rape

    -   Marital rape

    -   Second Shift

    -   Conversational maintenance work

-   Evaluation:

    -   Parsimonious: few concepts (gender, power, dominance).

    -   Limited explanability since it focuses on sex and gender, and limited utility: small subset of people.

Application:

[@Sanford_2019]

-   Based on Co-Cultural Theory, the authors found that even when they constitute a large part of an institution's
    population, Hispanic students still feel the need to behave under White norms (assimilationist strategies).

<br>

[@Ross_2016]

-   Modification s to office logistic and and practitioners' behavior can increase a healthy communication environment
    among trans-patient-practitioner

<br>

[@Nuru_2018]

-   memorable messages about race:

    -   denial of racism

    -   preparation for bias

    -   promotion of mistrust

-   these memorable message help make sense of racial hierarchies in Cost Rica and racial socialization in the global
    contexts.

<br>

[@Suter_2017]

Critical Interpersonal and Family Communication framework should consider:

-   power
-   bi-directionality between private and public realms
-   critique/resistance/transformation of the status quo in the service of social-justice ends
-   author reflexivity

"(a) What is my impetus for speaking and writing? (b) Where am I speaking from? (c) To whom am I accountable in this
process? (d) What are the potential material and discursive effects resulting from my speaking and writing" (Yep, 2010,
p. 173)
