# Organizational Change

This section is a summary and critique of "Organizational Change" by [@Lewis_2019]

Organizations are "socially constructed largely through the communicative interactions of internal and external
stakeholders".\
Stakeholders are those "who have a stake in an organization's process and or outputs".\
Ripple effects are "the impacts that organizational actions and presence bring to stakeholders within and surrounding
the organization".

Even though the fad nature of society values change and associate with positive terms, compared to negative connotations
of stability. However, changes does not equate good.\
Triggers for organizational changes:\
(external)

-   Legal requirements
-   Stakeholders
-   Current business, societal, environmental trends
-   Technologies
-   Availability of financial resources
-   Alteration of relationship, powers, and global economy.

(internal)

-   innovation
-   serendipity

Communication is key for changes because not until stakeholders recognize and communicate change that it materializes in
an organization.

Sensemaking is both "authoring" and interpretation [@Lewis_2019]. Communication among stakeholders is at the heart of
change processes in organizations because of this highly social process of making sense of what is going on and
"spinning it into narratives and theories of the world around us." [@Lewis_2019].

Costs of change:

-   Financial

-   Opportunities:

    -   Lost productivity
    -   Lost time in training works
    -   Workflow
    -   Loss of high value stakeholders.

-   Miscommunication: Confusion, fatigue.

-   Brand

[@Zorn_1999, p.10] define organizational change as "any alteration or modification of organizational structures or
processes."

Process of change:

-   Innovation: (creating) idea generation
-   Adoption: (deciding) formal decision by leaders
-   Diffusion: (sharing) sharing of ideas.
-   Implementation: "the translation of any tool or technique, process, or method of doing, from knowledge to practice."
    [@Tornatzky_1982]
-   Discontinuation: later, changes will become obsolete and a new cycle begins.

Communication is at the heart of all of these phases.

For relationships between innovation, diffusion, adoption, and implementation, check [@Lewis_2019, pp. 35]

Types of Organizational change:

-   Planned vs. unplanned changes

-   Objects that are changed (e.g., technologies, programs, policies, processes, personal). But not good in practice due
    to blur lines among these objects.

-   Discursive change (i.e., new label for old things to fake change) vs. material change (i.e., real changes in terms
    of operations, practices, relationships, decision-making) [@Zorn_1999, pp.10]

-   Size and scope of change [@Bartunek_1987] (however, size and scope can be subjective):

    -   First-order changes: small

    -   Second-order changes: large transformations, disruptive

    -   Third-order changes: continuous change.

Combinations of these types of organizational change can be viewed in [@Lewis_2019, pp. 42]

Complexity of change within organizations:

-   Interdependence: " The degree to which stakeholders impact the lives of other stakeholders as they engage change."
    [@Lewis_2019]

    -   Sequential Interdependence: Stakeholders affect one another in sequence (e.g., assembly line).
    -   Reciprocal interdependence: stakeholder's input are another stakeholder's outputs and vice versa. (e..g,
        co-authors).

-   organizational structures:

    -   Structures: are rules and resources (e.g., information, status, organizational beliefs, ) that create
        organizational practices

    -   Types of Structures:

        -   Decision-making patterns
        -   Decision-making processes
        -   Ladders of authority
        -   Role relationships
        -   Information-sharing norms
        -   Communication networks
        -   Reward system

-   Politics

Key processes in communication of planned change

-   Dissemination of information
-   Soliciting input
-   Socialization

Types of communication in change implementation

-   Formal Communication
-   Informal Communication: "includes spontaneous interactions of stakeholders with each other, with implementers, and
    with non-stakeholders."

change requires the following resources:

-   Physical
-   Financial
-   Emotional
-   Political
-   Rhetorical and discursive

**Processes** are "sets of actions designed and directed toward some desired outcome"

**Communication processes** consist of

-   interaction
-   discourse
-   interpretation

Communication processes in the context of change:

-   information dissemination: is used to reduce uncertainty

    -   Uncertainty is defined as "a lack of information or as confusion related to many available possible
        interpretations of events or objects."

    -   Change comes with [@Bordia_2003]:

        -   Strategic Uncertainty (e.g., relation to the external environment)

        -   Structural Uncertainty (e.g., culture)

        -   Job-related Uncertainty

    -   However, uncertainty is not always bad, or arises from lack of information. **Equivocality** (i.e., ambiguous
        meanings and overwhelming available interpretations of events or objects) can be troublesome too.

    -   Solution offered by [@Weick_2015] that focuses on processes of interpretation construction

        -   arguing

        -   expecting

        -   committing

        -   manipulating

    -   Knowledge in organizational change:

        -   [@Kuhn_2008] defines **knowledge** (a noun) as stable facts, objects, and dispositions, and **knowing** (a
            verb): an active and ongoing accomplishment of problem solving.

-   **soliciting**

    -   input from stakeholder can:

        -   lower resistance to change

        -   increase satisfaction of participants

        -   increase stakeholders' feelings of control

        -   reduce uncertainty about change.

    -   to maximize input, we can adopt **USER**:

        -   **Use** input as a resource in the decision-making process

        -   **Systematically** collect input

        -   **Evaluate** the the process

        -   **Rigorously** examine collected input

    -   voice can be

        -   full voice: actual, meaningful engagements by stakeholders

        -   limited voice: when changes are easily made or aligned with the implementer' idea.

        -   faux voice: channels to vent, but not material changes

    -   implementer can treat stakeholder participation as:

        -   symbol

        -   resource

    -   Authenticity and trust perception influences on the likelihood and how stakeholders will give inputs.

+--------------------------------------------------------------------+-------------------------------------------------+
| Direct (individuals represent themselves)                          | Indirect (representative for a group)           |
+====================================================================+=================================================+
| Forced (providers are required to participate)                     | Voluntary (individuals offer freely)            |
+--------------------------------------------------------------------+-------------------------------------------------+
| Formal (committees or task forces)                                 | Informal (water-cooler moments)                 |
+--------------------------------------------------------------------+-------------------------------------------------+
| publicly and identified (open staff meeting)                       | Privately or anonymous (privately to a          |
|                                                                    | consultant)                                     |
+--------------------------------------------------------------------+-------------------------------------------------+
| highly structured (questionnaire)                                  | unstructured (open, fluid conversion)           |
+--------------------------------------------------------------------+-------------------------------------------------+
| Listening (focused (implementer just listening)                    | Question/Answer focused (implementer            |
|                                                                    | responding)                                     |
+--------------------------------------------------------------------+-------------------------------------------------+
| Ongoing (throughout change process)                                | single opportunity (at a moment in time0        |
+--------------------------------------------------------------------+-------------------------------------------------+
| widespread (diverse stakeholders)                                  | selective (chosen few stakeholders)             |
+--------------------------------------------------------------------+-------------------------------------------------+
| minimal feedback to providers ( lack of response to issues raised) | frequent feedback (routine response)            |
+--------------------------------------------------------------------+-------------------------------------------------+
| Structured analysis of collected input (designed process fore      | Cursory review of input (casual or absent       |
| review)                                                            | review)                                         |
+--------------------------------------------------------------------+-------------------------------------------------+

: [@Lewis_2019, pp.75]

+---------------------------------+---------------------------+--------------------------------------------------------+
|                                 | Symbol                    | Resource                                               |
+=================================+===========================+========================================================+
| Select Stakeholder Involvement  | bankrupt Participation    | Privileged empowerment                                 |
+---------------------------------+---------------------------+--------------------------------------------------------+
| Diverse stakeholder involvement | ritualistic Participation | widespread empowerment (e.g., ideal speech situation)  |
+---------------------------------+---------------------------+--------------------------------------------------------+

: [@Lewis_2019, pp.77]

+----------------------------------+------------------------------------------------------+---------------------------+
|                                  | Low/Moderate value for fidelity                      | High value for fidelity   |
|                                  |                                                      |                           |
|                                  | (commitment to stick with the intended changed)      |                           |
+==================================+======================================================+===========================+
| Low resource Orientation         | Open                                                 | Restricted                |
+----------------------------------+------------------------------------------------------+---------------------------+
| Moderate Resource Orientation    | Political                                            | Advisory                  |
+----------------------------------+------------------------------------------------------+---------------------------+
| High Resource Orientation        | Widespread empowerment                               |                           |
+----------------------------------+------------------------------------------------------+---------------------------+

where [@Lewis_2011]

-   **socialization**

    -   "how organizations shape the understanding its members have of the values, priorities, procedures, job tasks,
        culture, and formal and informal expectations."

    -   Two types of person's adjustment:

        -   Personal Development (i.e., change frame of reference, values, or other attributes to fit into role)

        -   Role Development (i.e., change the role to fit with personal needs, abilities, and identity)

    -   From 2 types of adjustment lead to 4 adjustment modes:

        -   Replication: minimal adjustment to both role and person

        -   Absorption: change self to fit role

        -   Determination: change role to fit self

        -   Exploration: change both role and self.

<br>

Stakeholder Theory

Main branches:

-   Descriptive approach: describe relationships among stakeholders
-   Instrumental approach: "how organizational actions shape stakeholder relationship"
-   Normative approach: moral and ethical obiligations. (e.g., CSR).

Stakeholders are defined by 3 attributes [@mitchell1997]:

-   power
-   legitimacy
-   urgency

because stakeholders have multiple identities and they can salient at the time of change. Implementers noticing those
identities and appeal to them can be more advantageous than those who can't.

Communication is the means by which negotiative process to achive mutal goal are conceived. [@DEETZ_2001]

Types of roles:

-   Opinion leaders vs. innovation assassin

-   Connectors

-   Counselors:

    -   Emotional support

    -   Information support

    -   Instrumental support (i.e., doing some tasks for your peers).

-   Journalists

Outcome of change:

-   it's important to set goals

-   outcomes are assessed based on

    -   effectiveness: accomplishment

    -   efficiency: with the least amount of resources

-   To assess outcomes, we need to consider

    -   Timing

    -   Perspectives (of which stakeholders). Solution: should prob adopt one perspective.

        -   Survival of an org is the ultimate success, but the notion equifinality (i.e., multiple paths lead to the
            same end) comes into the picture

    -   Success measurement: sometimes can be intractable

    -   Attribution errors

    -   Documenting failure

Adopting technology:

-   Faithful appropriation: consistent with how the technology should be used.
-   Unfaithful appropriation: inconsistent with how the technology should be used.

Dimensions of change outcome:

-   Fidelity: "the degree of departure from the intended design of the change."
-   Uniformity: "the range of use of the change across adopting unit(s) or stakeholder groups."

Inauthenticity of stakeholders leads to suppression of inputs, in turn, leads to increases in stress, burnout, emotional
exhaustion,a nd depression. [@Lewis_2019, pp. 142]

<br>

Communication strategies

-   Adoptive approaches: fit the change to the organization
-   programmed approaches: fit the organization to the change
-   rule-bound approaches: centralized control
-   autonomous approaches: decentralized control

Structured implementation activities are "a set of actions purposefully designed and carried out to introduce users to
the innovation and to encourage intended usage [@lewis1993]

Types of change [@higgs2005] leadership behaviors :

-   Shaping behavior: authoritative
-   Framing Change: give starting points
-   creating capacity: give people space to make connections.

Communication Strategy Dimensions

-   Disseminating info/ soliciting feedback

-   Sideness: one-sided or two-sided message. To avoid **mum effect,** communicators sometimes use euphemism, which has
    evidently led to worse results

-   gain or loss frame: should not constantly "chicken little" or rose-colored glasses".

-   blanket (e.g., equal dissemination, equal participation) /targeted message (e.g., Quid pro quo, marketing, need to
    know)

-   discrepancy/efficacy: need to justify that change is needed, and the organization's capability for successful
    change.

    -   performance gap (current situation and ideal performance)

    -   identity gap (current schema and ideal schema): change acceptance zone.

Channels for communicating:

-   Interpersonal channel: face-to-face : typically in the integration phase
-   Mediated channels: some form of mass media or technology. typically in the action phase of implementation.

Power:

-   Power derives from the mutual dependence, and interdependence.

-   [@j.boonstra1998, pp. 99] defines power as "dynamical social process affecting opinions, emotions, and behavior of
    interest groups in which inequalities are involved with respect the realization of wishes and interests."

-   Power and latent power (i.e., the existence of power) can both affect compliance.

-   bases of power:

    -   position/assigned authority

    -   expertise, competency, and experience

    -   standards, protocols, and professional expectations

    -   norms, culture and tradition

    -   resource control

    -   reward control

    -   unique knowledge

    -   strong-tie networks of loyalists

    -   coalition membership.

-   balances of power: stakeholders does not want to yield their power.

    -   Concertive control: based on loyalty employees to put the org's interests before theirs.

    -   discourse (e.g., innovation).

Dimensions of resistance:

-   Cognitive

-   Emotional

-   Behavioral

Forms of resistance: run from subtle forms to forceful forms. **Principled dissent** should be encouraged to foster
safeguard against self-delusion and groupthinking.

Antecedents of communicators' strategies in the context of organizational change:

-   Institutional factors

    -   Isomorphism (i.e., "a constraining process that gives rise to similarity in organizational form and practice")

        -   Mimetic forces

        -   Coercive

        -   Normative

-   implementer' perceptions of the change context

    -   Assessing

        -   stakeholders and their values

        -   needs for consensus-building

        -   needs for efficiency

        -   individual and organizational change history and readiness

        -   goals for change

-   stakeholders' perceptions of the change context

    -   should create readiness early on

        -   beliefs by stakeholders:

            -   discrepancy: change is necessary

            -   appropriateness: change under consideration is the right one

            -   efficacy: the change within our reach

            -   principal support: commitment of decision-makers to the change

            -   valance.

Storytelling is to

-   make sense (i.e., sensemaking)
-   give that sense to others (i.e., sensegiving)

Narratives (i.e., stories) [@czarniawska1998a] has

-   an original state of affairs
-   an action or event
-   the consequent state of affairs

Tamara: the sensemaking path through an organization. [@David_2008]

Framing:

-   cognitive frame: in our heads
-   interactional frame: co-construction of meaning in ongoing interaction.

Implementers should take on an active role of meaning managers.

General concerns during change:

-   Uncertainty concerns: issues related to uncertainty of change
-   Performance concerns: ability to perform
-   Normative concerns: group norms will surface. the process of change, not the change itself can also violate norms.

Activity tracks during change

-   managing meaning
-   managing network
-   managing practice: actual physical implementation

Although we talked in this book extensively about change. However, changes are not always good. Sometimes, traditions
are in place for a reason or reasons: If something works for a long time, it is likely to be robust. More on this idea
can be read in Nassim Taleb's books.
